package DBclass;

public interface IDB_connection {
    //**************************************
    //DATABASE CONNECTION FOR THE PACESETTER
    //**************************************
    String DB_NAME = "pacesetterfx";
    String USER = "root";
    String DATABASE_PASSWORD = "Yabs2030";
    String CONNECTION_STRING = "jdbc:mysql://localhost:3306/" + DB_NAME;



    //Searching for the employee using the ID number
    //TABLE FOR THE ACCOUNTS OR MEMBERS DETAILS
    String TABLE_ACCOUNTS = "accounts";
    String COLUMN_ACCOUNTS_SIRNAME = "sir_name";
    String COLUMN_ACCOUNTS_MIDDLENAME = "middle_name";
    String COLUMN_ACCOUNTS_LASTNAME = "last_name";
    String COLUMN_ACCOUNTS_IDNUMBER = "id_number";
    String COLUMN_ACCOUNTS_EMAIL = "email_Address";
    String COLUMN_ACCOUNTS_PASSWORD = "password";
    String COLUMN_ACCOUNTS_PHOTO = "user_photo";
    String COLUMN_ACCOUNTS_PHONE_NUMBER = "phone_Number";
    String COLUMN_ACCOUNTS_BIRTHDAY = "birthday";
    String COLUMN_ACCOUNTS_ZIPCODE = "zipcode";
    String COLUMN_ACCOUNTS_ADDRESS = "Address";
    String COLUMN_ACCOUNTS_HOBBIES = "Hobbies";
    String COLUMN_ACCOUNTS_OCCUPATION = "occupation";
    String COLUMN_ACCOUNTS_MOREDETAILS = "AOD";
    String COLUMN_ACCOUNTS_COUNTRY = "Country";
    String COLUMN_ACCOUNTS_CITY = "City";

    int INDEX_ACCOUNTS_SIRNAME = 1;
    int INDEX_ACCOUNTS_MIDDLENAME = 2;
    int INDEX_ACCOUNTS_LASTNAME = 3;
    int INDEX_ACCOUNTS_IDNUMBER = 4;
    int INDEX_ACCOUNTS_EMAIL = 5;
    int INDEX_ACCOUNTS_PASSWORD = 6;
    int INDEX_ACCOUNTS_PHOTO = 7;

    String SEARCH_ID_QUERY = "SELECT * FROM " + DB_NAME +"."+TABLE_ACCOUNTS + " where " + COLUMN_ACCOUNTS_IDNUMBER + " = \"";
    String SEARCH_EMPLOYEE = "SELECT * FROM " + TABLE_ACCOUNTS;
    String LOGIN_QUERY = "SELECT * FROM " + DB_NAME+"."+TABLE_ACCOUNTS + " WHERE " + COLUMN_ACCOUNTS_EMAIL + " = \"";
    String GET_RECORDS_FROM_ACCOUNTS = "select * from pacesetterfx.accounts where id_number = ";
    String UPDATE_USER_PROFILE_PHOTO = "UPDATE `pacesetterfx`.`accounts` SET `user_photo` = ? WHERE (`id_number` = ?);";
    String UPDATE_SURNAME = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_SIRNAME +" = ";//'Oum' WHERE (`id_number` = ";//'12345678');";
    String UPDATE_MIDDLENAME = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_MIDDLENAME +" = ";
    String UPDATE_LASTNAME = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_LASTNAME +" = ";
    String UPDATE_PHONE_NUMBER = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_PHONE_NUMBER +" = ";
    String UPDATE_ADDRESS = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_ADDRESS +" = ";
    String UPDATE_PASSWORD = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_PASSWORD +" = ";
    String UPDATE_HOBBIES = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_HOBBIES +" = ";
    String UPDATE_AOB = "UPDATE "+DB_NAME+"."+TABLE_ACCOUNTS +" SET "+ COLUMN_ACCOUNTS_MOREDETAILS +" = ";
    String CONFIRM_EMAIL = "SELECT * FROM "+DB_NAME+"."+TABLE_ACCOUNTS+" where "+COLUMN_ACCOUNTS_EMAIL+" = ";
    String CONFIRM_PASSWORD = "SELECT * FROM "+DB_NAME+"."+TABLE_ACCOUNTS+" where "+COLUMN_ACCOUNTS_PASSWORD+" = ";


    //CREDITED ACCOUNTS SQL STRUCTURE
    //******************************
    String TABLE_CREDITED = "credited_accounts";
    String COLUMN_CREDITED_ID_NUMBER = "ID_NUMBER";
    String COLUMN_CREDITED_AMOUNT = "AMOUNT";
    String COLUMN_CREDITED_BALANCE = "BALANCE";
    String COLUMN_CREDITED_STATUS = "STATUS";
    String COLUMN_CREDITED_DATE = "DATE";

    //TABLE FOR THE TRANSACTION CREDITED OR THE MONTHLY PAYMENT
    String TABLE_TRANSACTION_CREDITED = "transaction_credited";
    String COLUMN_TRANSACTION_ID_NUMBER = "ID_NUMBER";
    String COLUMN_TRANSACTION_AMOUNT = "AMOUNT";

    //TABLE FOR MONTHLY GRAPH
    String TABLE_GRAPHMONTH = "monthlygraph";
    String COLUMN_GRAPHMONTH_AMOUNT = "AMOUNT";
    String COLUMN_GRAPHMONTH_DATE = "AMTDATE";

    //TABLE FOR CONSTANT AMOUNT CONTRIBUTED BY THE MEMBERS
    String TABLE_CON_AMOUNT = "constant_amount";
    String COLUMN_COL_AMT = "col_conAMOUNT";
    String COLUMN_CONSTANT_AMOUNT = "AMOUNT";

//    public static final double defaultAmount = 500;

    //The SQL string is used to get the sirname, lastname, idNumber, amount, balance, status
    String SELECT_DETAILS = "select * from " + DB_NAME+"."+ TABLE_ACCOUNTS + " where " + COLUMN_CREDITED_ID_NUMBER +" =\"";
    String TABLE_QUERY = "SELECT a." + COLUMN_ACCOUNTS_MIDDLENAME +", a."+ COLUMN_ACCOUNTS_LASTNAME+", a."+COLUMN_ACCOUNTS_IDNUMBER+", c." +
            COLUMN_CREDITED_AMOUNT+", c."+COLUMN_CREDITED_BALANCE+", c."+COLUMN_CREDITED_STATUS+", c."+COLUMN_CREDITED_DATE +
            " from " + DB_NAME+"."+TABLE_ACCOUNTS +" AS a" +
            " JOIN " +DB_NAME+"."+TABLE_CREDITED + " AS c ON c." + COLUMN_CREDITED_ID_NUMBER+ " = a." +COLUMN_ACCOUNTS_IDNUMBER+";";
    String INSERT_QUERY_INTO_CREDITED_ACCOUNT = "INSERT INTO "+DB_NAME+"."+TABLE_CREDITED +" ( "+COLUMN_CREDITED_ID_NUMBER+", "+ COLUMN_CREDITED_AMOUNT+", "+ COLUMN_CREDITED_BALANCE+", "+ COLUMN_CREDITED_STATUS+", "+ COLUMN_CREDITED_DATE +" )" +
            " VALUES ( ";
    String CHECK_PENDING_ACCOUNTS = "select * from " + DB_NAME+"."+TABLE_CREDITED+" where "+COLUMN_CREDITED_STATUS+" = 'PENDING' and "+COLUMN_CREDITED_ID_NUMBER+" = \"";
    String MONTHLY_GRAPH = "select "+COLUMN_GRAPHMONTH_AMOUNT+", "+"monthname("+COLUMN_GRAPHMONTH_DATE+") from "+DB_NAME+"."+TABLE_GRAPHMONTH+" where year("+COLUMN_GRAPHMONTH_DATE+") = "+ java.time.LocalDate.now().getYear() +" group by month("+COLUMN_GRAPHMONTH_DATE+") order by "+COLUMN_GRAPHMONTH_DATE+";";
    String YEAR_GRAPH = "select year(date) 'DATE', sum(amount) 'AMOUNT' from pacesetterfx.credited_accounts group by year(date) order by year(date) asc;";
    String MONTHLY_TOTAL_DEPOSIT = "INSERT INTO " + DB_NAME+"."+TABLE_GRAPHMONTH+" ("+COLUMN_GRAPHMONTH_AMOUNT+", "+COLUMN_GRAPHMONTH_DATE+") VALUES (";
    String GET_TOTAL_AMOUNT_CONTRIBUTED = "SELECT sum("+COLUMN_TRANSACTION_AMOUNT+") '"+COLUMN_TRANSACTION_AMOUNT+"' FROM "+DB_NAME+"."+TABLE_TRANSACTION_CREDITED+";";
    String SET_CONSTANT_AMOUNT = "SELECT "+COLUMN_CONSTANT_AMOUNT+" FROM "+DB_NAME+"."+TABLE_CON_AMOUNT+" where "+COLUMN_COL_AMT+" = 1 ";
    String UPDATE_CONSTANT_AMOUNT = "UPDATE `"+DB_NAME+"`.`"+TABLE_CON_AMOUNT+"` SET `"+COLUMN_CONSTANT_AMOUNT+"` = ";
    String GET_CONSTANT_FINE = "SELECT * FROM pacesetterfx.fine_constant where col_fine = 1";//1;";
    String UPDATE_FINE_CONSTANT = "UPDATE `pacesetterfx`.`fine_constant` SET `FINE_AMOUNT` = 200 WHERE `col_fine` = 1;";
    String MONTHLY_RECORDS = "SELECT date_format(DATE, '%M'), ID_NUMBER, sum(AMOUNT), BALANCE, STATUS  FROM pacesetterfx.credited_accounts  where ID_NUMBER "+"  = ";//34292991 and   DATE > now() - interval 12 month  group by AMOUNT, monthname(DATE)  order by DATE, ID_NUMBER;";
    String GET_TOTAL_MONTHLY_CONTRIBUTION = " select ID_NUMBER, sum(amount), DATE from pacesetterfx.credited_accounts where ID_NUMBER "+" = ";//12345678 and DATE > now() - interval 12 month;";
    String DISPLAY_BARGRAPH_CREDITED_ACCOUNT = "select sum("+COLUMN_GRAPHMONTH_AMOUNT+") from "+DB_NAME+"."+TABLE_GRAPHMONTH+";";
    String CREDIT_SINGLE_MONTH = "INSERT INTO `pacesetterfx`.`credited_accounts` (`ID_NUMBER`, `AMOUNT`, `BALANCE`, `STATUS`, `DATE`) VALUES (";//34327010, 3700, 0, 'OVERPAYED', '2021-09-04');";
    String INDIVIDUAL_TOTAL_AMOUNT = "select "+COLUMN_TRANSACTION_AMOUNT+" from "+DB_NAME+"."+TABLE_TRANSACTION_CREDITED+" where "+COLUMN_TRANSACTION_ID_NUMBER+" = ";
    String CURRENT_MONTH_CONTRIBUTION = "SELECT sum("+COLUMN_CREDITED_AMOUNT+") '"+COLUMN_CREDITED_AMOUNT+"' FROM "+DB_NAME+"."+TABLE_CREDITED+" where month("+COLUMN_CREDITED_DATE+") = "+ java.time.LocalDate.now().getMonthValue() +" AND ID_NUMBER = ";//34327010;";
    String ADD_AMOUNT_TO_ACCOUNT = "UPDATE `"+DB_NAME+"`.`"+TABLE_TRANSACTION_CREDITED+"` SET `"+COLUMN_TRANSACTION_AMOUNT+"` = `"+COLUMN_TRANSACTION_AMOUNT+"` + ";//500 WHERE ID_NUMBER = 34327010;";
    String CURRENT_MONTH_TOTAL_AMOUNT = "SELECT sum("+COLUMN_CREDITED_AMOUNT+") '"+COLUMN_CREDITED_AMOUNT+"' FROM "+DB_NAME+"."+TABLE_CREDITED+" where month("+COLUMN_CREDITED_DATE+") = "+ java.time.LocalDate.now().getMonthValue() +";";
    String UPDATE_PENDING_TRANSACTION = "UPDATE `"+DB_NAME+"`.`"+TABLE_CREDITED+"` SET ";
    //******************
    //LOAN SQL STRUCTURE
    //******************
    String TABLE_LOAN = "loan";
    String COLUMN_LOAN_ID_NUMBER = "ID_NUMBER";
    String COLUMN_LOAN_AMOUNT = "AMOUNT";
    String COLUMN_LOAN_BALANCE = "BALANCE";
    String COLUMN_LOAN_STATUS = "STATUS";
    String COLUMN_LOAN_DATE = "LOAN_DATE";
    String COLUMN_LOAN_PAID_DATE = "PAID_DATE";

    //TABLE FOR TRANSACTION LOAN
    String TABLE_TRANSACTION_LOAN = "transaction_loan";
    String COLUMN_TRANSACTION_LOAN_ID_NUMBER = "ID_NUMBER";
    String COLUMN_TRANSACTION_LOAN_AMOUNT = "AMOUNT";

    //TABLE FOR PERCENTAGE RATE %
    String TABLE_RATE = "rate";
    String COLUMN_RATE = "COL_RATE";
    String COLUMN_RATE_RATES = "RATE";

    String LOAN_INSERT_RECORD = "INSERT INTO "+DB_NAME+"."+TABLE_LOAN+" ("+COLUMN_LOAN_ID_NUMBER+", "+COLUMN_LOAN_AMOUNT+", "+COLUMN_LOAN_DATE+", "+COLUMN_LOAN_PAID_DATE+")" +
            "VALUES (";
    String UPDATE_RATE = "UPDATE "+DB_NAME+"."+TABLE_RATE+" SET "+COLUMN_RATE_RATES+" = ";// WHERE COL_RATE = 1 LIMIT 1;";
    String SET_RATE = "select "+COLUMN_RATE_RATES+" from "+DB_NAME+"."+TABLE_RATE+" where "+COLUMN_RATE+" = ";
    String LOAN_TABLE_QUERY = "SELECT "+COLUMN_LOAN_DATE+", "+ COLUMN_LOAN_PAID_DATE+", "+ COLUMN_LOAN_AMOUNT+", "+ COLUMN_LOAN_BALANCE+", "+ COLUMN_LOAN_STATUS +" FROM "+DB_NAME+"."+TABLE_LOAN+"  where "+COLUMN_LOAN_ID_NUMBER+" = ";
    String TOTAL_LOAN_AMOUNT = "SELECT sum("+COLUMN_TRANSACTION_LOAN_AMOUNT+") '"+COLUMN_TRANSACTION_LOAN_AMOUNT+"' FROM "+DB_NAME+"."+TABLE_TRANSACTION_LOAN+";";
    String LOAN_FOR_INDIVIDUAL = "SELECT "+COLUMN_TRANSACTION_LOAN_AMOUNT+" FROM "+DB_NAME+"."+TABLE_TRANSACTION_LOAN+" where "+COLUMN_TRANSACTION_LOAN_ID_NUMBER+" = ";//34327010;";
    String PAY_LOAN = "UPDATE "+DB_NAME+"."+TABLE_LOAN+" SET ";
    String SELECT_PENDING_LOAN = "select * from "+DB_NAME+"."+TABLE_LOAN+" where "+COLUMN_LOAN_STATUS+" = 'PENDING' AND "+COLUMN_LOAN_ID_NUMBER+" = ";
    String TOTAL_PENDING_LOAN = "select sum("+COLUMN_LOAN_AMOUNT+") '"+COLUMN_LOAN_AMOUNT+"' from "+DB_NAME+"."+TABLE_LOAN+" where `"+COLUMN_LOAN_STATUS+"` = 'PENDING' AND `"+COLUMN_LOAN_ID_NUMBER+"` = ";

    //******************
    //FINE SQL STRUCTURE
    //******************

    //TABLE FOR FINE_CREDIT
    String TABLE_FINE_CREDIT = "fine_credit";
    String COLUMN_FINE_ID_NUMBER = "ID_NUMBER";
    String COLUMN_FINE_AMOUNT = "CREDITED";
    String COLUMN_FINE_BALANCE = "BALANCE";
    String COLUMN_FINE_STATUS = "STATUS";
    String COLUMN_FINE_CREDIT_DATE = "CREDITED_DATE";
    String COLUMN_FINE_CREDIT_PAIDDATE = "PAID_DATE";

    //TABLE FOR TRANSACTION_FINE_LOAN
    String TABLE_TRANSACTION_FINE_LOAN = "transaction_fineloan";
    String COLUMN_TRANSACTION_FINE_ID_NUMBER = "ID_NUMBER";
    String COLUMN_TRANSACTION_FINE_AMOUNT = "AMOUNT";

    //TABLE FOR TRANSACTION_FINE_CREDITED
    String TABLE_TRANSACTION_FINE_CREDITED = "transaction_finecredited";
    String COLUMN_TRANSACTION_FINE_CREDITED_ID = "ID_NUMBER";
    String COLUMN_TRANSACTION_FINE_CREDITED_AMOUNT = "AMOUNT";

    //TABLE FOR FINE LOAN
    String TABLE_FINE_LOAN = "fine_loan";
    String COLUMN_FINE_LOAN_ID_NUMBER = "ID_NUMBER";
    String COLUMN_FINE_LOAN_AMOUNT = "LOAN_AMOUNT";
    String COLUMN_FINE_LOAN_BALANCE = "LOAN_BALANCE";
    String COLUMN_FINE_LOAN_STATUS = "STATUS";
    String COLUMN_FINE_LOAN_DATE = "LOAN_DATE";
    String COLUMN_FINE_LOAN_PAID_DATE = "PAID_DATE";

    String INSERT_FINE_LOAN_RECORDS = "INSERT INTO "+DB_NAME+"."+TABLE_FINE_LOAN+" ("+COLUMN_FINE_LOAN_ID_NUMBER+", "+COLUMN_FINE_LOAN_AMOUNT+", "+COLUMN_FINE_LOAN_BALANCE+", "+COLUMN_FINE_LOAN_DATE+") VALUES (";//34327010, 200, 100, '2021-09-03');";

    String INSERT_FINE_CREDIT_RECORDS = "INSERT INTO "+DB_NAME+"."+TABLE_FINE_CREDIT+" ("+COLUMN_FINE_ID_NUMBER+", "+COLUMN_FINE_AMOUNT+", "+COLUMN_FINE_BALANCE+", "+COLUMN_FINE_CREDIT_DATE+") VALUES (";//34327010, 450, 0, '2021-09-03');";
    String GET_PENDING_RECORDS_CREDITED_ACCOUNTS = "SELECT * FROM "+DB_NAME+"."+TABLE_CREDITED+" where "+COLUMN_CREDITED_STATUS+" = 'pending' and "+ COLUMN_CREDITED_ID_NUMBER +" = \"";
    String GET_RECORDS_PENDING_LOAN = "SELECT * FROM "+DB_NAME+"."+TABLE_LOAN+" where "+COLUMN_LOAN_STATUS+" = 'pending' and "+COLUMN_LOAN_ID_NUMBER+" = \"";
    String GET_FINE_LOAN_RECORDS = "SELECT sum("+COLUMN_TRANSACTION_FINE_AMOUNT+") '"+COLUMN_TRANSACTION_FINE_AMOUNT+"' FROM "+DB_NAME+"."+ TABLE_TRANSACTION_FINE_LOAN +";";
    String INDIVIDUAL_FINE_LOAN = "SELECT sum("+COLUMN_TRANSACTION_FINE_AMOUNT+") '"+COLUMN_TRANSACTION_FINE_AMOUNT+"' FROM "+DB_NAME+"."+ TABLE_TRANSACTION_FINE_LOAN +" where "+COLUMN_TRANSACTION_FINE_ID_NUMBER+" = ";
    String GET_FINE_MONTHLY_RECORDS = "SELECT * FROM "+DB_NAME+"."+TABLE_FINE_CREDIT+" where "+COLUMN_FINE_STATUS+" = 'PENDING' and "+COLUMN_FINE_ID_NUMBER+" = ";
    String GET_LOAN_FINE_RECORDS = "SELECT * FROM pacesetterfx.fine_loan where status = 'PENDING' and ID_NUMBER "+" = ";//34327010;";
    String FINE_CREDITED_ACCOUNT = "SELECT sum("+COLUMN_TRANSACTION_FINE_CREDITED_AMOUNT+") '"+COLUMN_TRANSACTION_FINE_CREDITED_AMOUNT+"' FROM "+DB_NAME+"."+TABLE_TRANSACTION_FINE_CREDITED+";";
    String CURRENT_CREDITED_FINE = "SELECT "+COLUMN_TRANSACTION_FINE_CREDITED_AMOUNT+" FROM "+DB_NAME+"."+TABLE_TRANSACTION_FINE_CREDITED+" WHERE "+COLUMN_TRANSACTION_FINE_CREDITED_ID+" = ";
    String SELECT_FINE_CREDITED = "SELECT * FROM "+DB_NAME+"."+TABLE_FINE_CREDIT+" where  "+COLUMN_FINE_STATUS+" = 'pending' AND "+COLUMN_TRANSACTION_FINE_CREDITED_ID+" = ";
    String UPDATE_FINE_CREDITED =  "UPDATE "+DB_NAME+"."+TABLE_FINE_CREDIT+" SET ";
    String TOTAL_CREDITED_FINE = "select sum("+COLUMN_FINE_AMOUNT+") '"+COLUMN_FINE_AMOUNT+"' from "+DB_NAME+"."+TABLE_FINE_CREDIT+" where "+COLUMN_FINE_STATUS+" = 'pending' and "+COLUMN_FINE_ID_NUMBER+" = ";
    String TOTAL_LOAN_FINE = "select sum("+COLUMN_FINE_LOAN_AMOUNT+") '"+COLUMN_FINE_LOAN_AMOUNT+"' from "+DB_NAME+"."+TABLE_FINE_LOAN+" where "+COLUMN_FINE_LOAN_STATUS+" = 'PENDING' AND `"+COLUMN_FINE_LOAN_ID_NUMBER+"` = ";
    String UPDATE_FINE_LOAN =  "UPDATE "+DB_NAME+"."+TABLE_FINE_LOAN+" SET ";
    String SELECT_FINE_LOAN_PENDING = "SELECT * FROM "+DB_NAME+"."+TABLE_FINE_LOAN+" where  "+COLUMN_FINE_LOAN_STATUS+" = 'pending' AND "+COLUMN_FINE_LOAN_ID_NUMBER+" = ";//34327010 order by LOAN_DATE asc limit 1;";
    String FINE_CREDITED = "INSERT INTO `"+DB_NAME+"`.`"+TABLE_FINE_CREDIT+"` (`"+COLUMN_FINE_ID_NUMBER+"`, `"+COLUMN_FINE_AMOUNT+"`, `"+COLUMN_FINE_BALANCE+"`, `"+COLUMN_FINE_STATUS+"`, `"+COLUMN_FINE_CREDIT_DATE+"`) ";

}
